// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID     int64       `db:"id" json:"id"`
	PostID pgtype.Int8 `db:"post_id" json:"post_id"`
	UserID pgtype.Int8 `db:"user_id" json:"user_id"`
	// Content of the comment
	Body      string             `db:"body" json:"body"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version   pgtype.Int8        `db:"version" json:"version"`
	Latest    bool               `db:"latest" json:"latest"`
}

type Permission struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version   pgtype.Int8        `db:"version" json:"version"`
	Latest    bool               `db:"latest" json:"latest"`
}

type Post struct {
	ID    int64  `db:"id" json:"id"`
	Title string `db:"title" json:"title"`
	// Content of the post
	Body      string             `db:"body" json:"body"`
	UserID    pgtype.Int8        `db:"user_id" json:"user_id"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version   pgtype.Int8        `db:"version" json:"version"`
	Latest    bool               `db:"latest" json:"latest"`
}

type Role struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version   pgtype.Int8        `db:"version" json:"version"`
	Latest    bool               `db:"latest" json:"latest"`
}

type RoleM2mPermission struct {
	ID           int64              `db:"id" json:"id"`
	RoleID       pgtype.Int8        `db:"role_id" json:"role_id"`
	PermissionID pgtype.Int8        `db:"permission_id" json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy    pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version      pgtype.Int8        `db:"version" json:"version"`
	Latest       bool               `db:"latest" json:"latest"`
}

type RoleM2mUser struct {
	ID        int64              `db:"id" json:"id"`
	RoleID    pgtype.Int8        `db:"role_id" json:"role_id"`
	UserID    pgtype.Int8        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version   pgtype.Int8        `db:"version" json:"version"`
	Latest    bool               `db:"latest" json:"latest"`
}

type User struct {
	ID                int64              `db:"id" json:"id"`
	Username          string             `db:"username" json:"username"`
	FullName          string             `db:"full_name" json:"full_name"`
	Email             string             `db:"email" json:"email"`
	HashedPassword    string             `db:"hashed_password" json:"hashed_password"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	IsEmailVerified   bool               `db:"is_email_verified" json:"is_email_verified"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         pgtype.Int8        `db:"created_by" json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy         pgtype.Int8        `db:"updated_by" json:"updated_by"`
	Version           pgtype.Int8        `db:"version" json:"version"`
	Latest            bool               `db:"latest" json:"latest"`
}
