// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePermission(ctx context.Context, id pgtype.Text) (Permission, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateRole(ctx context.Context, id pgtype.Text) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePermission(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetPermission(ctx context.Context, id int64) (Permission, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetUser(ctx context.Context, username pgtype.Text) (User, error)
	ListPermission(ctx context.Context) ([]Permission, error)
	ListPost(ctx context.Context) ([]Post, error)
	ListRole(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
